resources:    
  - name: vijay
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/dummy
      files:  # optional
        include: pipeline.*
      branches:  # optional
        include: master
        exclude: readme        
      tags:  # optional
        include: v.* 
      buildOn:  # optional
        commit: true
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
        tagCreate: true
      cancelPendingRunsOn:
        newCommit: true        
      shallowDepth: 1  # optional 

  - name: gitres
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/dummy
      files:  # optional
#         include: pipelines.sh
        exclude: readme
      branches:  # optional
        include: master 
        exclude: readme
      buildOn:  # optional
         commit: false
#          pullRequestCreate: true
#          pullRequestClose: true
#          releaseCreate: true
#          tagCreate: false
      cancelPendingRunsOn:
        newCommit: false
      shallowDepth: 10  # optional 

pipelines:

  - name: pipelines_true
  
    steps:
      - name: s_BashTriggerTrue
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: vijay
        execution:
          onExecute:
            - printenv 
            - pushd $res_vijay_resourcePath
            - git log
            - ls
            - cat pipelines.sh    

  - name: pipelines_false
  
    steps:
      - name: s_BashTriggerFalse
        type: Bash
        configuration:
          environmentVariables:
            env1: value1
            env2: value2
          inputResources:
            - name: gitres
        execution:
          onExecute:
            - printenv 
            - pushd $res_gitresource_resourcePath
            - git log
            - ls
            - cat pipelines.sh         
         

  


          
