resources:
  - name: test_1
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/runtime
      branches:     
        include: master            

pipelines:
  - name: pipelines_vijay_new
    steps:
      - name: S_Bash1
        type: Bash
        configuration: 
          inputResources:          
            - name: test_1234           
        execution:
          onExecute:
            - echo "executing step..."
            - printenv  
            - free -m
            
      - name: S_Bash2
        type: Bash
        configuration: 
          inputSteps:
            - name: S_Bash1
        execution:
          onExecute:
            - echo "executing step..."
            - printenv  


      - name: S_Bash3
        type: Bash
        configuration: 
          inputSteps:
            - name: S_Bash1            
        execution:
          onExecute:
            - echo "executing step..."
            - printenv 

