resources:
  - name: S_PS_R_GIT_0016_GitRepo1
    type: GitRepo
    configuration:
      gitProvider: s_gitHub
      path: vijayreddy1991/run

pipelines:
  - name: pipelines_S_PS_R_GIT_00161
    steps:
      - name: S_PS_R_GIT_0016
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: S_PS_R_GIT_0016_GitRepo1
        execution:
          onExecute:
#             - find_resource_variable $res_S_PS_R_GIT_0016_GitRepo1
            - get-childitem $res_S_PS_R_GIT_0016_GitRepo1
            - Get-Variable 
            - write-output "executing step..."
            - if($res_S_PS_R_GIT_0016_GitRepo1_lastAuthorEmail -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitProvider_token -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_isGitTag -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_commitUrl -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_shaData -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitProvider_id -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_integrationName -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_operation -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitRepoFullName -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitProvider_name -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitProvider_url -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitRepoSourceDefaultBranch -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_isTrigger -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_resourceId -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitProvider_masterName -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_commitSha -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_isPullRequest -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_path -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_isPrivateRepository -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_isPrerelease -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitRepoRepositorySshUrl -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_isRelease -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_committerLogin -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_integrationAlias -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_branchName -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_resourcePath -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_compareUrl -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_repositoryProvider -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_sysPrivateDeployKey -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_sysPublicDeployKey -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_lastAuthorLogin -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_beforeCommitSha -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitRepoRepositoryHttpsUrl -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_isPullRequestClose -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_gitRepoRepositoryUrl -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_masterName -eq $null){ Write-Error "Stop" -ErrorAction Stop}
            - if($res_S_PS_R_GIT_0016_GitRepo1_commitMessage -eq $null){ Write-Error "Stop" -ErrorAction Stop}
