pipelines:
  - name: S_Bash_0515
    steps:
      - name: S_Bash_0515
        type: Bash
        configuration:
          nodePool: c7dynamic
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - 16
        execution:
          onExecute:
            - docker images
            - |
              [[ "$step_image_name:$step_image_tag" == "releases-docker.jfrog.io/jfrog/pipelines-c7node:16" ]]
            - |
              [[ "$(node --version)" == *"$step_image_tag"* ]]
