
pipelines:
  - name: vijay_pipeline
    steps:
      - name: pipelines_ubuntu
        type: Bash         
        execution:
          onExecute: 
             - node --version 
             - printenv  
