resources:
  - name: git_vijaytest
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: master

pipelines:

  - name: vijay_super
    steps:
      - name: restore_pipelines1
        type: Bash 
        configuration: 
#           nodePool: vijay   
          inputResources:          
            - name: git_vijaytest         
        execution:
          onExecute:
            - printenv  
#             - sleep 120
#             - printen




