
pipelines:
  - name: vijay_pipeline
    steps:
      - name: pipelines_ubuntu
        type: Bash 
        configuration: 
#           nodePool: u18dynamic        
        execution:
          onExecute: 
             - node --version 
             - printenv  
