resources:
  - name: git_vijaytest
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: master
pipelines:
  - name: vijay_pipeline_test
    steps:
      - name: restore_pipelines1
        type: Bash 
        configuration: 
          nodePool: u18dynamic   
          inputResources:          
            - name: git_vijaytest         
        execution:
          onExecute:
            - printenv  
            - grep --version
