resources:
  - name: git_vijaytest
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: master
pipelines:
  - name: vijay_pipeline_ubuntu
    steps:
      - name: pipelines_ubuntu
        type: Bash 
        configuration: 
#           nodePool: u18dynamic   
          inputResources:          
            - name: git_vijaytest         
        execution:
          onExecute:         
             - printenv  

            
            
  - name: vijay_pipeline_windows
    steps:           
      - name: pipelines_windows
        type: Bash 
        configuration: 
          runtime:
            type: host        
          nodePool: win_2019  
          inputResources:          
            - name: git_vijaytest         
        execution:
          onExecute:
            - printenv       
            - echo "test1"
