resources:
  - name: git_vijaytest
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: master
pipelines:
  - name: vijay_pipeline_test
    steps:
      - name: pipelines1
        type: Bash 
        configuration: 
#           nodePool: u18dynamic   
          inputResources:          
            - name: git_vijaytest         
        execution:
          onExecute:         
             - printenv  
      - name: pipelines2
        type: Bash 
        configuration:  
          inputSteps:
            - name: pipelines1
          inputResources:          
            - name: git_vijaytest              
        execution:
          onExecute:
            - printenv     
            - sleep 60
            - echo "testing1"
            - sleep 60
            - echo "testing2"
      - name: pipelines4
        type: Bash 
        configuration:  
          inputSteps:
            - name: pipelines2
          inputResources:          
            - name: git_vijaytest              
        execution:
          onExecute:
            - printenv     
            - sleep 60
            - echo "testing1"
            - sleep 60
            - echo "testing2"
      - name: pipelines5
        type: Bash 
        configuration:  
          inputSteps:
            - name: pipelines5
          inputResources:          
            - name: git_vijaytest              
        execution:
          onExecute:
            - printenv     
            - sleep 60
            - echo "testing1"
            - sleep 60
            - echo "testing2"
            
            
           
      - name: pipelines3
        type: Bash 
        configuration: 
          runtime:
            type: host        
#           nodePool: u18dynamic   
          inputResources:          
            - name: git_vijaytest         
        execution:
          onExecute:
            - printenv       
            - sleep 60
            - echo "test1"
