resources:
  - name: vijaykumar
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run            
pipelines:
  - name: vijay_test
    steps:
      - name: S_vijay
        type: Bash #PowerShell
        configuration: 
          nodePool: k8_u16dynamic        
          inputResources:
            - name: vijaykumar
#           runtime:
#             type: host
         
        execution:
          onExecute:
            - echo "executing step..."
#             - df -h
#             - docker images
#             - cd /opt
#             - pwd
#             - docker images
#             - df -h
#             - docker pull drydock/u16all:master
#             - df -h
#             - docker pull drydock/u16javall:master
#             - df -h
#             - docker pull drydock/u16phpall:master
#             - df -h
#             - docker pull drydock/u16scaall:master
#             - df -h
#             - docker pull drydock/u16nodall:master
#             - df -h
#             - docker pull drydock/u14:master
#             - df -h
#             - docker pull drydock/u14all:master
#             - df -h
#             - docker pull drydock/u14javall:master
#             - df -h
#             - docker pull drydock/u14phpall:master
#             - df -h
#             - docker pull drydock/u14scaall:master
#             - df -h
#             - docker pull drydock/u14nodall:master
#             - df -h
#             - docker pull drydock/c7:master
#             - df -h
#             - docker pull drydock/u14all:master
#             - df -h
#             - docker pull drydock/c7all:master
#             - df -h
#             - docker pull drydock/c7javall:master
#             - df -h
# #             - docker pull drydock/c7phpall:master
# #             - df -h
# #             - docker pull drydock/c7scaall:master
# #             - df -h
# #             - docker pull drydock/c7nodall:master
# #             - df -h
# #             - docker pull drydock/u18node:master
# #             - df -h
# #             - docker pull drydock/u16node:master
# #             - df -h
# #             - docker pull ubuntu
# #             - df -h
#           onSuccess:
#             - echo "Job well done!"   
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
#       - name: test
#         type: Bash
#         configuration:
#           integrations:
#             - name: vijay_gitHub
#           inputResources:
#             - name: vijay
            
#         execution:
#           onExecute: 
#             - pushd $res_vijay_resourcePath 
#             - mkdir savetests
#             - pushd savetests
#             - pwd
#             - touch test.xml
#             - echo "hello frog" > test.xml    
#             - ls
#             - popd
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
# #             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
# #             - save_tests $res_vijay_resourcePath/savetests/test.xml            
#             - popd

#       - name: test2
#         type: Bash
#         configuration:
#           integrations:
#             - name: vijay_gitHub
#           inputSteps:
#             - name: test
#           inputResources:
#             - name: vijay                
#         execution:
#           onExecute:
#             - printenv
#             - pushd $res_vijay_resourcePath
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
# #             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
#             - save_tests $res_vijay_resourcePath/jfrog         
#             - popd

#       - name: test3
#         type: Bash
#         configuration:
#           integrations:
#             - name: vijay_gitHub
#           inputResources:
#             - name: vijay
#           inputSteps:
#             - name: test2          

#         execution:
#           onExecute:
#             - pushd $res_vijay_resourcePath
#             - touch test.xml
#             - echo "fgjhkggfyifyfhgfghjyity" > test.xml
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
#             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
#             - save_tests $res_vijay_resourcePath/test.xml  
#             - cat test.xml
#             - ls -la
#             - popd
           
#       - name: power
#         type: Bash
#         configuration:        
#           inputResources:
#             - name: vijay
            
#         execution:
#           onExecute: 
#             - pushd $res_vijay_resourcePath    
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
#             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
#             - save_tests $res_vijay_resourcePath            
#             - popd

#       - name: power2
#         type: bash
#         configuration:
#           integrations:
#             - name: vijay_gitHub
#           inputSteps:
#             - name: power
#           inputResources:
#             - name: vijay                
#         execution:
#           onExecute:
#             - printenv
#             - pushd $res_vijay_resourcePath
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
#             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
#             - save_tests $res_vijay_resourcePath/jfrog         
#             - popd

#       - name: power3
#         type: Bash
#         configuration:      
#           integrations:
#             - name: vijay_gitHub            
#           inputResources:
#             - name: vijay
#           inputSteps:
#             - name: power2         

#         execution:
#           onExecute:
#             - pushd $res_vijay_resourcePath
#             - python -m py_compile calc.py
#             - pip install --upgrade pip
#             - hash -d pip
#             - pip install pytest           
#             - py.test --verbose --junit-xml test-reports/results.xml test_calc.py
#             - save_tests $res_vijay_resourcePath/test-reports/jfrog.yml  
#             - popd
            


#       - name: powershell
#         type: PowerShell
#         configuration:
#           nodePool: win_2019        
#           integrations:
#             - name: vijay_gitHub            
#           inputResources:
#             - name: vijay
# #           inputSteps:
# #             - name: power2  
#         execution:
#           onExecute: 
#             - get-childitem $res_vijay_resourcePath
#             - choco install python2
#             - python --version
#             - python -m pip install --upgrade pip
#             - pip --version
#             - pip install pytest
#             - pytest --version
#             - Push-Location $res_vijay_resourcePath
#             - get-childitem $res_vijay_resourcePath
# #             - get-childitem tests/core/sampleExecutionFile
#             #- pytest tests/test_sample.py
#             - py.test --verbose --junit-xml test-reports/results.xml test_sample.py
            
#             - Get-Content -Path test-reports/results.xml
            
#       - name: powershell2
#         type: PowerShell
#         configuration:
#           nodePool: win_2019        
#           integrations:
#             - name: vijay_gitHub            
#           inputResources:
#             - name: vijay
#           inputSteps:
#             - name: powershell  
#         execution:
#           onExecute:             
#             - get-childitem $res_vijay_resourcePath
#             - choco install python2
#             - python --version
#             - python -m pip install --upgrade pip
#             - pip --version
#             - pip install pytest
#             - pytest --version
#             - Push-Location $res_vijay_resourcePath
#             - get-childitem $res_vijay_resourcePath
# #             - get-childitem tests/core/sampleExecutionFile
#             #- pytest tests/test_sample.py
#             - py.test --verbose --junit-xml test-reports/results.xml test_sample.py
            
# #             - Get-Content -Path test-reports/results.xml            
#             - save_tests $res_vijay_resourcePath

#       - name: powershell3
#         type: PowerShell
#         configuration:
#           nodePool: win_2019        
#           integrations:
#             - name: vijay_gitHub            
#           inputResources:
#             - name: vijay
#           inputSteps:
#             - name: powershell2  
#         execution:
#           onExecute:             
#             - get-childitem $res_vijay_resourcePath
#             - choco install python2
#             - python --version
#             - python -m pip install --upgrade pip
#             - pip --version
#             - pip install pytest
#             - pytest --version
#             - Push-Location $res_vijay_resourcePath
#             - get-childitem $res_vijay_resourcePath
# #             - get-childitem tests/core/sampleExecutionFile
#             #- pytest tests/test_sample.py
#             - py.test --verbose --junit-xml test-reports/results.xml test_sample.py           
#             - save_tests $res_vijay_resourcePath/test-reports
            
#       - name: powershell4
#         type: PowerShell
#         configuration:
#           nodePool: win_2019        
#           integrations:
#             - name: vijay_gitHub            
#           inputResources:
#             - name: vijay
#           inputSteps:
#             - name: powershell3  
#         execution:
#           onExecute:             
#             - get-childitem $res_vijay_resourcePath
#             - choco install python2
#             - python --version
#             - python -m pip install --upgrade pip
#             - pip --version
#             - pip install pytest
#             - pytest --version
#             - Push-Location $res_vijay_resourcePath
#             - get-childitem $res_vijay_resourcePath
# #             - get-childitem tests/core/sampleExecutionFile
#             #- pytest tests/test_sample.py
# #             - py.test --verbose --junit-xml test-reports/results.xml test_sample.py           
#             - save_tests $res_vijay_resourcePath    
            
#       - name: powershell5
#         type: PowerShell
#         configuration:
#           nodePool: win_2019        
#           integrations:
#             - name: vijay_gitHub            
#           inputResources:
#             - name: vijay
#           inputSteps:
#             - name: powershell4  
#         execution:
#           onExecute:             
#             - get-childitem $res_vijay_resourcePath
#             - choco install python2
#             - python --version
#             - python -m pip install --upgrade pip
#             - pip --version
#             - pip install pytest
#             - pytest --version
#             - Push-Location $res_vijay_resourcePath
#             - get-childitem $res_vijay_resourcePath
# #             - get-childitem tests/core/sampleExecutionFile
#             #- pytest tests/test_sample.py
# #             - py.test --verbose --junit-xml test-reports/results.xml test_sample.py           
#             - save_tests $res_vijay_resourcePath/tests  
           
            
#       - name: powershell6
#         type: PowerShell
#         configuration:
#           nodePool: win_2019        
#           integrations:
#             - name: vijay_gitHub            
#           inputResources:
#             - name: vijay
#           inputSteps:
#             - name: powershell5  
#         execution:
#           onExecute:             
#             - get-childitem $res_vijay_resourcePath
#             - choco install python2
#             - python --version
#             - python -m pip install --upgrade pip
#             - pip --version
#             - pip install pytest
#             - pytest --version
#             - Push-Location $res_vijay_resourcePath
#             - get-childitem $res_vijay_resourcePath
# #             - get-childitem tests/core/sampleExecutionFile
#             #- pytest tests/test_sample.py
# #             - py.test --verbose --junit-xml test-reports/results.xml test_sample.py            
#             - Set-Content -Path "$res_vijay_resourcePath/test.xml" -Value "ghjhkggyibgj" 
#             - get-childitem $res_vijay_resourcePath
#             - get-Content $res_vijay_resourcePath/test.xml
#             - save_tests $res_vijay_resourcePath/test.xml 
