resources:
  - name: git_vijaytest
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: master
pipelines:
  - name: vijay_pipeline_test
    steps:
      - name: pipelines1
        type: Bash 
        configuration: 
#           nodePool: u18dynamic   
          inputResources:          
            - name: git_vijaytest         
        execution:
          onExecute:
          
            - printenv  
      - name: pipelines2
        type: Bash 
        configuration:  
          inputSteps:
            - name: pipelines1
        execution:
          onExecute:
            - printenv  
            
            
            
            
#       - name: pipelines3
#         type: Bash 
#         configuration: 
# #           nodePool: u18dynamic   
#           inputResources:          
#             - name: git_vijaytest         
#         execution:
#           onExecute:
#             - printenv              
