resources:
      
  - name: vijayRepo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      
  - name: mypropertyBag
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      key3: value3
      key4: value4      

pipelines:
  - name: vijay_pipeline
    steps:

      - name: vijay_step1
        type: Bash
        configuration: 
          nodePool: u16dynamic          
          inputResources:
            - name: vijayRepo
            - name: mypropertyBag

        execution:
          onExecute:
            - echo "testvariable"
            - printenv

      - name: vijay_step2
        type: Bash
        configuration: 
          nodePool: u16dynamic          
          inputResources:
            - name: vijayRepo
            - name: mypropertyBag

        execution:
          onExecute:
            - echo "testvariable"
            - printenv
            
      - name: vijay_step2
        type: Bash
        configuration: 
          nodePool: u16dynamic          
          inputResources:
            - name: vijayRepo
            - name: mypropertyBag

        execution:
          onExecute:
            - echo "testvariable"
            - printenv            

