resources:
  - name: vijayRepo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run      
  - name: mypropertyBag
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
      key3: value3
      key4: value4      

pipelines:
  - name: vijay_pipeline
    steps:

      - name: node_step1
        type: Bash
        configuration:         
          inputResources:
            - name: vijayRepo
            - name: mypropertyBag
        execution:
          onExecute:
            - echo "testvariable"
            - printenv

      - name: node_step2
        type: Bash
        configuration:         
          inputResources:
            - name: vijayRepo
            - name: mypropertyBag
          inputSteps:
            - name: node_step1              
        execution:
          onExecute:
            - echo "testvariable"
            - printenv
            
      - name: node_step3
        type: Bash
        configuration:        
          inputResources:
            - name: vijayRepo
            - name: mypropertyBag
          inputSteps:
            - name: node_step2              
        execution:
          onExecute:
            - echo "testvariable"
            - printenv            
