
# pipelines:
#   - name: vijay_world
#     steps:
#       - name: first
#         type: Bash
#         execution:
#           onExecute:
#             - echo "hello"
#       - name: second
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: first
#         execution:
#           onExecute:
#             - echo "Hello World"
#       - name: third
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: second
#         execution:
#           onExecute:
#             - echo "hello"
#       - name: four
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: third
#         execution:
#           onExecute:
#             - echo "Hello World"
#       - name: five
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: four
#         execution:
#           onExecute:
#             - echo "hello"
#       - name: six
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: five
#         execution:
#           onExecute:
#             - echo "Hello World"
#       - name: seven
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: six
#         execution:
#           onExecute:
#             - echo "hello"
#       - name: eight
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: seven
#         execution:
#           onExecute:
#             - echo "Hello World"
#       - name: nine
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: eight
#         execution:
#           onExecute:
#             - echo "hello"
#       - name: ten
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: nine
#         execution:
#           onExecute:
#             - echo "Hello World"


pipelines:
  - name: N_DyNodepoolTest
    steps:
      - name: N_DyNodepoolTest
        type: Bash
        configuration:
          nodePool: AWS_dynamic_U20_sanity
        execution:
          onExecute:
            - echo "executing step..."    
      - name: N_DyNodepoolTest_u20
        type: Bash
        configuration:
          nodePool: AWS_dynamic_U20_sanity
          inputSteps:
            - name: N_DyNodepoolTest           
        execution:
          onExecute:
            - echo "executing step..."
      - name: N_DyNodepoolTest_c7
        type: Bash
        configuration:
          nodePool: AWS_dynamic_C7_Sanity
          inputSteps:
            - name: N_DyNodepoolTest         
        execution:
          onExecute:
            - echo "executing step..."
      - name: N_DyNodepoolTest_w19
        type: PowerShell
        configuration:
          nodePool: AWS_dynamic_win19_Sanity
          inputSteps:
            - name: N_DyNodepoolTest             
        execution:
          onExecute:
            - echo "executing step..."
      - name: N_DyNodepoolTest_gcp_c7
        type: Bash
        configuration:
          nodePool: GCP_dynamic_C7_Sanity
          inputSteps:
            - name: N_DyNodepoolTest             
        execution:
          onExecute:
            - echo "executing step..."
      - name: N_DyNodepoolTest_gcp_u20
        type: Bash
        configuration:
          nodePool: GCP_dynamic_U20_Sanity
          inputSteps:
            - name: N_DyNodepoolTest             
        execution:
          onExecute:
            - echo "executing step..."  
