resources:
  - name: jfrog_playground
    type: GitRepo
    configuration:
      gitProvider: aiOla_GitHub_Enterprise
      path: aiola-lab/jfrog-playground
      branches:
        include: development
      buildOn:
        commit: true
        pullRequestCreate: true
        pullRequestClose: false
      cancelPendingRunsOn:
        newCommit: false
        pullRequestUpdate: true
  - name: service_a_propertyBag
    type: PropertyBag
    configuration:
      success: "false"
  - name: service_b_propertyBag
    type: PropertyBag
    configuration:
      success: "false"            
pipelines:            
  - name: top_embed_pipeline
    steps:
      - name: compare_git
        type: Bash
        configuration:
          inputResources:
            - name: jfrog_playground
              trigger: true
        execution:
          onExecute:
            # - add_run_variables service_a="true"
            - add_run_variables service_b="true"
      - name: trigger_service_a
        type: TriggerPipeline
        configuration:
          condition: 'service_a == "true"'
          pipelineName: service_a
          stepName: scan_it
          integrations:
            - name: artifactory_pipelines
          environmentVariables:
            scan_target: "test1"
          inputSteps:
            - name: compare_git
              status:
                - success
        execution:
          onStart:
            - set_trigger_payload pipelineVariables "scan_target=${scan_target}"
          onComplete:
            - echo "Final status is $nested_run_status"
      - name: trigger_service_b
        type: TriggerPipeline
        configuration:
          condition: 'service_b == "true"'
          pipelineName: service_b
          stepName: scan_it
          integrations:
            - name: artifactory_pipelines
          environmentVariables:
            scan_target: "test2"
          inputSteps:
            - name: compare_git
              status:
                - success
        execution:
          onStart:
            - set_trigger_payload pipelineVariables "scan_target=${scan_target}"            
          onComplete:
            - echo "Final status is $nested_run_status"            
      - name: laststep
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_service_a
              status:
                - success
                - skipped
            - name: trigger_service_b            
              status:
                - success
                - skipped
          inputResources:
            - name: service_a_propertyBag
              trigger: false
            - name: service_b_propertyBag
              trigger: false
        execution:
          onExecute:
            - echo "*** $res_service_a_propertyBag_success ***"
            - echo "*** $res_service_b_propertyBag_success ***"
  - name: service_a
    steps:
      - name: scan_it
        type: Bash
        configuration:
          inputResources:
            - name: jfrog_playground
              trigger: false
          outputResources:
            - name: service_a_propertyBag            
        execution:
          onExecute:
            - echo "$res_jfrog_playground_branchName"
            - echo "$res_jfrog_playground_commitMessage"
            - echo "$res_jfrog_playground_commitSha"
            - echo "$res_jfrog_playground_isPullRequest"
            - echo "$res_jfrog_playground_pullRequestNumber"
            - echo "Image to scan is $scan_target. !!!"
            - echo "Triggered by parent step at $parent_step_url"
            - echo "*** $res_service_a_propertyBag_success ***"
          onSuccess:
            - echo "Holla onSuccess!!!"
            - write_output ${pipeline_name}_propertyBag success="true"
  - name: service_b
    steps:
      - name: scan_it
        type: Bash
        configuration:
          inputResources:
            - name: jfrog_playground
              trigger: false        
          outputResources:
            - name: service_b_propertyBag                          
        execution:
          onExecute:
            - echo "$res_jfrog_playground_branchName"
            - echo "$res_jfrog_playground_commitMessage"
            - echo "$res_jfrog_playground_commitSha"
            - echo "$res_jfrog_playground_isPullRequest"
            - echo "$res_jfrog_playground_pullRequestNumber"
            - echo "Image to scan is $scan_target. !!!"
            - echo "Triggered by parent step at $parent_step_url"
            - echo "*** $res_service_b_propertyBag_success ***"
          onSuccess:
            - echo "Holla onSuccess!!!"
            - write_output ${pipeline_name}_propertyBag success="true"
