resources:
  - name: test_1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run       

pipelines:
  - name: vijay_pipeline_ubuntu
    steps:
      - name: run
        type: Bash
        configuration:    
          runtime:
            type: host
          inputResources:
            - name: test_1234
        execution:
          onExecute: 
             - echo "testing"
             - ls -la
             - pushd $res_test_1234_resourcePath
             - cd opt/jfrog/pipelines
             - ls -la
             - cd time
             - cat start.txt
             - cat build.txt
