resources:
  - name: test_1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
      branches:     
        include: ^(bugfix|feature)\/.*$

pipelines:
  - name: vijay_pipeline_ubuntu
    steps:
      - name: pipelines_ubuntu
        type: Bash
        configuration: 
          environmentVariables:
            RT_VERSION: 7.46.3
            MASTER_KEY: "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"
            JOIN_KEY: "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE"         
          inputResources:          
            - name: test_1234           
        execution:
          onFaiure:
            - echo cheppura
          onExecute: 
             - node --version 
             - printenv
             # - if commit sha is 000000 then do something; else do something else
             - |
              if [ "$res_test_1234_commitSha" == "0000000000000000000000000000000000000000"]; then
                echo foo
              else
                echo bar
              fi
