resources:
  - name: exclude
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run
        
pipelines:
  - name: test_gcp_nodepool
    steps:
      - name: host_machine_step
        type: Bash
        configuration:         
          inputResources:
            - name: exclude
        execution:
          onExecute: 
             - echo "testing"
#              # - docker --version
#              # - node --version
#              # - npm --version
#              # - npm list -g kind-of
#              # - npm list -g json5
#              # - npm list -g elliptic
      - name: Docker_step
        type: Bash
        configuration:
          # nodePool: win_2019
          runtime:
            type: image
          inputSteps:
            - name: host_machine_step
        execution:
          onExecute: 
             - echo "testing"
             - docker images
#              - cat logs.txt
#              - cat startlogs.txt          
