resources:
  - name: test_1234
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/run       

pipelines:
  - name: test_gcp_nodepool
    configuration:  
      # runtime:
      #   type: host
    steps:
      - name: run
        type: Bash
        configuration:    
          runtime:
            type: image
          inputResources:
            - name: test_1234
        execution:
          onExecute: 
             - echo "testing"
             - uname -m
             - lscpu
             - docker images
             # - docker --version
             # - node --version
             # - npm --version
             # - npm list -g kind-of
             # - npm list -g json5
             # - npm list -g elliptic
             
#              - pushd $res_test_1234_resourcePath
#              - cd /var/opt/jfrog/pipelines
#              - ls -la
#              - cd time
#              - ls -la
# #              - cat download.txt
#              - cat start.txt
#              - cat logs.txt
#              - cat startlogs.txt
#       - name: powershell
#         type: PowerShell
#         configuration:
#           nodePool: win_2019
#           runtime:
#             type: host
#           inputResources:
#             - name: test_1234
#         execution:
#           onExecute: 
#              - echo "testing"
#              - ls -la
#              - pushd $res_test_1234_resourcePath
#              - cd /var/opt/jfrog/pipelines
#              - ls -la
#              - cat time.txt
# #              - cat logs.txt
# #              - cat startlogs.txt             
